function [cids, cgs] = readClusterGroupsCSV(filename)
% READCLUSTERGROUPSCSV Read cluster group classifications from CSV/TSV file
%
%   [cids, cgs] = readClusterGroupsCSV(filename)
%
%   Parses cluster group files generated by Phy or Kilosort.
%
%   Parameters:
%     filename - Path to cluster_groups.csv or cluster_group.tsv
%
%   Returns:
%     cids - Cluster IDs (numeric vector)
%     cgs  - Cluster groups (0=noise, 1=mua, 2=good, 3=unsorted)
%
%   See also: loadKSdir

fid = fopen(filename);
C = textscan(fid, '%s%s');
fclose(fid);

cids = cellfun(@str2num, C{1}(2:end), 'uni', false);
ise = cellfun(@isempty, cids);
cids = [cids{~ise}];

isUns = cellfun(@(x)strcmp(x,'unsorted'),C{2}(2:end));
isMUA = cellfun(@(x)strcmp(x,'mua'),C{2}(2:end));
isGood = cellfun(@(x)strcmp(x,'good'),C{2}(2:end));
cgs = zeros(size(cids));

cgs(isMUA) = 1;
cgs(isGood) = 2;
cgs(isUns) = 3;

end
