"""Parse Kilosort/Phy params.py files.

Ports loadParamsPy.m. The params.py file is a Python-syntax config file
generated by Kilosort, containing variables like sample_rate, n_channels_dat, etc.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def load_params_py(path: str | Path) -> dict[str, Any]:
    """Load a Kilosort params.py file and return its variables as a dict.

    Parameters
    ----------
    path : path to params.py

    Returns
    -------
    dict with keys like 'sample_rate', 'n_channels_dat', 'dtype', 'hp_filtered', etc.
    """
    params: dict[str, Any] = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip()
            # Parse value
            if val.lower() == "true":
                params[key] = True
            elif val.lower() == "false":
                params[key] = False
            elif val.startswith("'") or val.startswith('"'):
                params[key] = val.strip("'\"")
            else:
                try:
                    params[key] = int(val)
                except ValueError:
                    try:
                        params[key] = float(val)
                    except ValueError:
                        params[key] = val
    return params
